### ISSUE TITLE
some elements are not keyboard accessible in Safari on MacOS

### ISSUE THREAD

**Issue by bruffridge** [nasa-petal/bidara-deep-chat#96]
links in initialMessages, popup menu items, deep-chat's attachment and mic buttons.

**Comment by jackitaliano** [comment]
It seems this is expected behavior in Safari.

Safari by default does not put anchor tags in the tab order, even if you set `tabindex="0"`. 

Pressing `Option + Tab` will use the full tab order, including those anchor tags. This also works if you go to Safari Settings -> Advanced -> Select "Press Tab to highlight each item on a webpage", in which case it will reverse this so `Tab` acts as `Option + Tab` and vice versa.

However, deep-chat's attachment and mic buttons are working for me on Safari without doing either of these things. They are rather far down in the tab order, especially with many chats open, so could it have just been that for you? Or are they actually not working? Not sure why they'd work for me an not you.

To fix this, I could make the links in the menu Buttons instead, but I'm not sure how that would affect accessibility since they are just links.
I could not change how deep-chat handles links. Deep-chat links are handled by rendering html from markdown, so even they do not handle that.

**Comment by bruffridge** [comment]
Attachment and mic buttons are working now, I must've been using cached assets. I didn't know Safari handled tab order differently. All is well, so closing the issue.
